;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;
;==========================================================

include-file = ~/.cache/wal/colors-polybar

[bar/example]
width = 100%
height = 18pt
radius = 1

background = #CC000000
foreground = ${colors.foreground}

line-size = 3pt

border-size = 2pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = "JetBrainsMono Nerd Font:size=10;2"
font-1 = "Hack;2"

modules-left = xworkspaces xwindow
modules-right = pulseaudio memory cpu battery date bluetoothmenu networkmenu powermenu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces

enable-click = true
enable-scroll = true

label-active = %name%
label-active-background = ${colors.background}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %mountpoint% %percentage_used%%
label-mounted-foreground = ${colors.primary}

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "  " 
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume =  %percentage%%

label-muted =  muted
label-muted-foreground = ${colors.disabled}

[module/memory]
type = internal/memory
interval = 2

format-prefix = "RAM " 
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%


[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}



[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>

label-disconnected = %ifname% disconnected
label-disconnected-foreground = ${colors.disabled}

[module/wlan]
inherit = network-base
interface-type = wireless

label-connected = %ifname% %essid% %local_ip%
label-connected-foreground = ${colors.primary}

[module/eth]
inherit = network-base
interface-type = wired

label-connected = %ifname% %local_ip%
label-connected-foreground = ${colors.primary}

[module/date]
type = internal/date
interval = 1

date = %I:%M %p
date-alt = %A, %d %B %Y  %I:%M %p

label =  %date%
label-foreground = ${colors.primary}


[settings]
screenchange-reload = true
pseudo-transparency = false

[module/battery]
type = internal/battery

battery = BAT0
adapter = AC

full-at = 98
low-at = 15

format-charging = <label-charging>
format-discharging = <label-discharging>
format-full = <label-full>

label-charging =   %percentage%%
label-discharging =   %percentage%%
label-full =   100%

label-charging-foreground = ${colors.primary}
label-discharging-foreground = ${colors.foreground}
label-full-foreground = ${colors.disabled}

[module/powermenu]
type = custom/text

format = " ⏻ "
content-padding = 1

click-left = ~/.config/rofi/power-menu.sh

[module/networkmenu]
type = custom/text

format = "   "
content-padding = 1
content-foreground = ${colors.primary}

click-left = st -e nmtui

[module/bluetoothmenu]
type = custom/text

format = "  " 
content-padding = 1
content-foreground = ${colors.primary}

click-left = st -e bluetui


; vim:ft=dosini

