#!/bin/sh

awk '
/MemTotal/     { total=$2 }
/MemAvailable/ { avail=$2 }
END {
    used = total - avail
    if (used > 1048576)
        printf "󰍛 %.1f GB", used/1048576
    else
        printf "󰍛 %d MB", used/1024
}
' /proc/meminfo

